### ISSUE TITLE
Bug(s): `Home` Page 🐛

### ISSUE THREAD

**Issue by gracebilliris** [SIS-Team-24/2023-SIS-Team-24#128]
Tasks:
- [x] Only show _sentiment anlaysis of the text is: ...._ and _emotion analysis result: ..._ once the `Sentiment` _button_ is pressed.
- [x] The `Sentiment` _button_ can be pressed when the _Text to be Summarised_ is empty.
- [x] Reduce the _height_ of the _textboxes_.

**Comment by srujankarthik** [comment]
Resolves #171
