### ISSUE TITLE
Researching Feature: PDF Input for Text to be Summarised.

### ISSUE THREAD

**Issue by gracebilliris** [SIS-Team-24/2023-SIS-Team-24#156]

**Comment by henrygoodman** [comment]
pdf.js: This is an open-source library that allows you to extract text from a PDF file by parsing the file and extracting the text content from it. You can use the getTextContent() method to extract the text from a PDF file.

react-pdf: This is a React-specific library that provides a set of components for displaying and extracting text from PDF files. You can use the TextLayer component to extract text from a PDF.

pdf-parse: This is a JavaScript library that allows you to extract text, images and other data from a PDF file. It also supports extracting text from a specific page and area of the pdf.

pdf-extract: This is a library that allows you to extract text, images, and other data from a PDF file. It supports extracting text from specific pages and coordinates of the pdf.

pdf-text-extract: This is a library that allows you to extract text from a pdf file, it's simple and easy to use.
