### ISSUE TITLE
Manual Testing for Text Insights

### ISSUE THREAD

**Issue by Kyrus2504** [SIS-Team-24/2023-SIS-Team-24#174]

**Comment by Kyrus2504** [comment]
[Manual Testing for Text Insights.docx](https://github.com/SIS-Team-24/2023-SIS-Team-24/files/12840040/Manual.Testing.for.Text.Insights.docx)

Still need to add:
[x] - How Acceptance Criteria was tested
[x] - Overall Findings

**Comment by gracebilliris** [comment]
#98
