### ISSUE TITLE
Emotion Analysis Text Colour

### ISSUE THREAD

**Issue by henrygoodman** [SIS-Team-24/2023-SIS-Team-24#192]
![image](https://github.com/SIS-Team-24/2023-SIS-Team-24/assets/79623665/2abe17c0-ad57-4e71-a652-de52b5e772b5)

Difficult to see black text on dark backgrounds.
Perhaps can be changed to use white text on all backgrounds determined as dark

**Comment by stephenb-coding** [comment]
Resolved in https://github.com/SIS-Team-24/2023-SIS-Team-24/pull/203
