### ISSUE TITLE
(Manual) E2E Testing

### ISSUE THREAD

**Issue by gracebilliris** [SIS-Team-24/2023-SIS-Team-24#201]

**Comment by gracebilliris** [comment]
Example: this is the problem.
Screenshot: [HERE].
Assignee to solve: [NAME].

**Comment by Rgonzales4** [comment]
Issue: Removing the black placeholder box + hiding share URL before summary is made.
Assignee: @Rgonzales4 

![Image](https://github.com/SIS-Team-24/2023-SIS-Team-24/assets/44883385/faaf8585-e627-4d17-8426-f3f624285cfb)

**Comment by henrygoodman** [comment]
Issue: The newlines on this text placeholder is not consistent, sometimes looks weird

```
placeholder=
" Enter 100 words or more to summarise...
──────────── OR ────────────
Drag and drop a PDF file to use as input..."
```

Assignee: @henrygoodman 

Fixed by #203 (I hope, if someone can check, my PC always show it working)

**Comment by henrygoodman** [comment]
Issue: IMO the space between the URL input and the below textarea title is too small, can increase it

![image](https://github.com/SIS-Team-24/2023-SIS-Team-24/assets/79623665/0f0794f6-3f7a-477b-9cf4-c3eafc859842)

Assignee: @gracebilliris

**Comment by Rgonzales4** [comment]
Issue: All values in UI not clearing when logo is clicked
Reporter: @gracebilliris 
Assignee: @Rgonzales4
