### ISSUE TITLE
Remove matrix from CI

### ISSUE THREAD

**Issue by henrygoodman** [SIS-Team-24/2023-SIS-Team-24#57]
So I had no idea that Actions minutes were limited

Time is money and to save money in this cost of living crisis we are going to reduce all our CI to running on one matrix version

Node 18
Python3.11

🦖

**Comment by gracebilliris** [comment]
How does this get effected with the new repo settings?

**Comment by henrygoodman** [comment]
> How does this get effected with the new repo settings?

I think actions minutes are back to unlimited now, so we dont need to merge the PR, however since it makes very little difference, I am happy to merge the PR just for the reason that not running on pushes now means less time waiting overall

**Comment by gracebilliris** [comment]
Yes, we now have unlimited cause we are a public repo.
